export const colors = [
    { name: 'Red', value: 'rgb(146, 7, 7)' },
    { name: 'Red', value: 'red' },
    { name: 'Green', value: 'rgb(89, 255, 0)' },
    { name: 'Aqua', value: 'rgb(0, 255, 251)' },
    { name: 'Blue', value: 'rgb(8, 0, 255)' },
    { name: 'Red', value: 'red' },
    { name: 'Orange', value: 'orange' },
    { name: 'Yellow', value: 'yellow' },
    { name: 'Green', value: 'green' },
    { name: 'Blue', value: 'rgb(255, 0, 234)' },
    { name: 'Purple', value: 'purple' },
    { name: 'Yellow', value: 'yellow' },
    { name: 'Green', value: 'rgb(110, 223, 110)' },
    { name: 'Blue', value: 'rgb(255, 0, 111)' },
    { name: 'Purple', value: 'rgb(128, 0, 47)' },
    { name: 'Red', value: 'rgb(146, 7, 7)' },
    { name: 'Red', value: 'red' },
    { name: 'Green', value: 'rgb(89, 255, 0)' },
    { name: 'Aqua', value: 'rgb(0, 255, 251)' },
    { name: 'Blue', value: 'rgb(8, 0, 255)' },
    { name: 'Red', value: 'red' },
    { name: 'Orange', value: 'orange' },
    { name: 'Yellow', value: 'yellow' },
  ];